souvenirs/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using souvenirs.Models;

namespace souvenirs.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

souvenirs/Controllers/MemberSouvenirController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using souvenirs.Data;
using souvenirs.Models;
using Microsoft.AspNetCore.Authorization;
using System.Net.Http.Headers;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using System.IO;

namespace souvenirs.Controllers
{
    [AllowAnonymous]
    [Authorize(Roles = "Member")]

    public class MemberSouvenirController : Controller
    {
        private readonly ApplicationDbContext _context;

        public MemberSouvenirController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: MemberSouvenir
        public async Task<IActionResult> Index(int? categoryId, string currentFilter, string searchString, int? page, decimal? minPrice, decimal? maxPrice)
        {

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewData["CurrentFilter"] = searchString;
            ViewData["CurrentCategory"] = categoryId;//put category id into current filter
            ViewData["minPrice"] = minPrice;
            ViewData["MaxPrice"] = maxPrice;

            var souvenirs = from s in _context.Souvenirs
                            select s;

            if (!String.IsNullOrEmpty(searchString))
            {
                souvenirs = souvenirs.Where(s => s.Name.Contains(searchString));
            }

            //return View(await _context.Souvenirs.ToListAsync());
            if (categoryId.HasValue)
            {
                souvenirs = souvenirs.Where(s => s.CategoryID == categoryId);
            }
            if (minPrice.HasValue)
            {
                souvenirs = souvenirs.Where(s => s.Price >= minPrice);
            }
            if (maxPrice.HasValue)
            {
                souvenirs = souvenirs.Where(s => s.Price <= maxPrice);
            }
            var categories = _context.Categories
                .AsNoTracking();

            ViewBag.Categories = categories;

            int pageSize = 3;
            return View(await PaginatedList<Souvenir>.CreateAsync(souvenirs.AsNoTracking(), page ?? 1, pageSize));
        }

        // GET: MemberSouvenir/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var souvenir = await _context.Souvenirs
                .Include(s => s.Category)
                .Include(s => s.Supplier)
                .SingleOrDefaultAsync(m => m.ID == id);
            if (souvenir == null)
            {
                return NotFound();
            }

            return View(souvenir);
        }

        // GET: MemberSouvenir/Create
        public IActionResult Create()
        {
            ViewData["CategoryID"] = new SelectList(_context.Categories, "ID", "ID");
            ViewData["SupplierID"] = new SelectList(_context.Suppliers, "ID", "ID");
            return View();
        }

        // POST: MemberSouvenir/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Name,Price,Image,Description,CategoryID,SupplierID")] Souvenir souvenir)
        {
            if (ModelState.IsValid)
            {
                _context.Add(souvenir);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryID"] = new SelectList(_context.Categories, "ID", "ID", souvenir.CategoryID);
            ViewData["SupplierID"] = new SelectList(_context.Suppliers, "ID", "ID", souvenir.SupplierID);
            return View(souvenir);
        }

        // GET: MemberSouvenir/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var souvenir = await _context.Souvenirs.SingleOrDefaultAsync(m => m.ID == id);
            if (souvenir == null)
            {
                return NotFound();
            }
            ViewData["CategoryID"] = new SelectList(_context.Categories, "ID", "ID", souvenir.CategoryID);
            ViewData["SupplierID"] = new SelectList(_context.Suppliers, "ID", "ID", souvenir.SupplierID);
            return View(souvenir);
        }

        // POST: MemberSouvenir/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Name,Price,Image,Description,CategoryID,SupplierID")] Souvenir souvenir)
        {
            if (id != souvenir.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(souvenir);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SouvenirExists(souvenir.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryID"] = new SelectList(_context.Categories, "ID", "ID", souvenir.CategoryID);
            ViewData["SupplierID"] = new SelectList(_context.Suppliers, "ID", "ID", souvenir.SupplierID);
            return View(souvenir);
        }

        // GET: MemberSouvenir/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var souvenir = await _context.Souvenirs
                .Include(s => s.Category)
                .Include(s => s.Supplier)
                .SingleOrDefaultAsync(m => m.ID == id);
            if (souvenir == null)
            {
                return NotFound();
            }

            return View(souvenir);
        }

        // POST: MemberSouvenir/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var souvenir = await _context.Souvenirs.SingleOrDefaultAsync(m => m.ID == id);
            _context.Souvenirs.Remove(souvenir);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SouvenirExists(int id)
        {
            return _context.Souvenirs.Any(e => e.ID == id);
        }
    }
}

souvenirs/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About Us";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>


<span style="color:green;font-size:18px">About Us</span>
<p>
    Our company was established in 1965 with our original family owners continuing to be involved. Now with over 40 years experience servicing the tourist industry, offering quality gifts, art works, clothing and mementos for tourists, travellers, and locals alike. Our company is proudly 100% kiwi owned and operated. We have grown to become New Zealand’s largest tourist retailer, currently with 17 stores across the north and south Islands in Auckland, Rotorua, Napier, Wellington, Nelson, Wanaka, and Christchurch. We have now completed the process and final re-branding of our stores in 2018, from The Great New Zealand Shop to Simply New Zealand and New Zealand The Gift across the country.

    Our gift and souvenirs range is diverse and promotes New Zealand and our way of life. Our stores cater for travellers from overseas looking for mementos to take home that are a reminder of their stay in Aotearoa, or gifts for friends and family with a particular New Zealand flavour. Be it artworks, skincare, toys, jewellery, clothing New Zealand natural skincare ranges; Manuka Honey, and Rotorua Mud to name a few. New Zealanders are proud to embrace uniquely New Zealand items for their own homes or to take overseas for friends or loved ones. Business people also purchase items from our stores as corporate gifting or to take overseas as gifts for business colleagues.
</p>
        Customer service is a key focus for us. We provide quality products and want to ensure our customers’ expectations are exceeded when they shop with us. Our staff are courteous, motivated, and trained to provide excellent service. Our business is backed by our close-knit management team.

<br />
<br />
<br />
<span style="color:green;font-size:18px">Why Shop with Us?</span>


<p>
    Our Stores are Quality Assured and Accredited
    Our merchandise range and service is underpinned by our ‘Satisfaction Guaranteed’ policy. We are a Qualmark Endorsed Visitor Service. After we championed the brand to make sure retail could be included, our group of stores became the first Qualmark accredited retailer in New Zealand since 1965, and we are active members of Tourism Industry Aotearoa, 100% Pure New Zealand, and Retail NZ.
    We are Locally Recognised
    Our Nelson store, which was opened in 2005, has won the Nelson Mall Top Shop awards twice. In 2013 it not only won the Homeware, Giftware and Specialty Store section, it was also named the overall winner. The judges said that the store had received perfect scores on two visits and commented that the staff had been friendly and helpful without being pushy. The store attracts lots of tourists, but also has the ‘Nelson family’ of loyal customers – many who have been shopping there since the store opened.

    We are a Trusted New Zealand Retailer
    Family owned and operated, we’ve upheld a trustworthy reputation as one of New Zealand’s largest tourism retail companies since 1965

    We offer Fast Local Shipping | TAX FREE Worldwide Delivery Options
    Fast local and reliable shipping to all New Zealand addresses and locations. We offer TAX FREE purchasing for all online shopping cart items when delivery is selected to a worldwide address/outside of New Zealand. (NZ GST is currently 15% and may be subject to changes). Please contact us office@touristgroup.co.nz in regards to freight costs for orders needing to be sent worldwide (excluding Australia).

</p>
<br />
<br />
<span style="color:green;font-size:18px">Our Mission Statement</span>
<p>
    Our mission statement is 'Sharing memories and experiences of New Zealand' by providing excellence in service and quality of merchandise that exceeds our customers expectations, so as to ensure they leave us with pleasant memories of our stores, our products, our country and with the desire to revisit us. We take pride in our stores and strive to be the best in customer service, product range and professional attitude.

</p>
<ul>
    <li>Offering Quality NZ Made Products</li>

    <li>  Internationally recognised New Zealand designer clothing brands</li>

    <li>Art, woodware, and giftware items created by locally renowned artists and craftspeople</li>

    <li>Branded apparel and unique gifts exclusive only to our stores</li>

    <li> Best in customer service, product range and professional attitude</li>

    <li>Carefully selected categories of jewellery, mementos and gifts reflective of New Zealand</li>

</ul>

souvenirs/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact Us";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>


<div class="container">
    <h6>Simply New Zealand | New Zealand Quality Souvenir</h6>

    <br />
    Head Office:   Managing Director 183 Building, Unitec

    <br />
    Mt Albert New Zealand
    <br />
    <br />
    Ph: +64 1234 567"
    <br />
    Fax: +64 123 4567"
    <div>
        <br />
        Email:
        <a href="/">office@souvenir.com</a>
    </div>
    <a href="/" data-googletools="1"><span style="color:#56aa1c;">CLICK HERE FOR ALL STORE LOCATIONS | CONTACTS</span></a>
</div>

souvenirs/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
        <li data-target="#myCarousel" data-slide-to="3"></li>
    </ol>
    <div class="carousel-inner" role="listbox" style="border-radius:50%;">
        <div class="item active">
            <img src="~/images/souvenir7.jpg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
               
            </div>
        </div>
        <div class="item">
            <img src="~/images/souvenir3.jpg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                
            </div>
        </div>
        <div class="item">
            <img src="~/images/carousel2.png" alt="Package Management" class="img-responsive" />
            <div class="carousel-caption" role="option">
                
            </div>
        </div>
        <div class="item">
            <img src="~/images/souvenir8.jpg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
               
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>
<br />
<br />


<section class="container-fluid row">
    <div class="col-xs-12 col-s-12 col-md-4 col-lg-4 col-xl-4" style="border:1px solid lightgrey">
        <div class="card" style="width: 400px;height:480px;">
            <h3 class="text-center">our products</h3>
            <img style="width:350px;border-radius:50%;"class="card-img-top" src="~/images/souvenir6.jpg" alt="Card image cap">
            <br />
            <div class="card-body text-align" style="margin:30px">
                <a asp-area="" asp-controller="MemberSouvenir" asp-action="Index" class="btn btn-success" style="width:100px;margin-left:80px;">View More</a>
            </div>
        </div>
        
    </div> 

    <div class="col-xs-12 col-s-12 col-md-4 col-lg-4 col-xl-4" style="border:1px solid lightgrey">
        <div class="card" style="width: 400px;height:480px;">
            <h3 class="text-center">feel free to contact</h3>
            <img style="width:350px;border-radius:50%;" class="card-img-top" src="~/images/carousel1.jpg" alt="Card image cap">
            <br />
            <div class="card-body text-align" style="margin:30px">
                <a asp-area="" asp-controller="Home" asp-action="Contact" class="btn btn-success" style="width:100px;margin-left:80px;">get in touch</a>
            </div>
        </div>
    </div>

    <div class="col-xs-12 col-s-12 col-md-4 col-lg-4 col-xl-4" style="border:1px solid lightgrey">
        <div class="card" style="width: 400px;height:480px;">
            <h3 class="text-center">Know more about us</h3>
            <img style="width:350px;border-radius:50%;margin-top:40px;" class="card-img-top" src="~/images/gift4.jpg" alt="Card image cap">
            <br />
            <div class="card-body text-align" style="margin:30px">
                <a asp-area="" asp-controller="Home" asp-action="About" class="btn btn-success" style="width:100px;margin-left:80px;">About Us</a>
            </div>
        </div>
    </div>
</section>