souvenirs/Models/Souvenir.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;


namespace souvenirs.Models
{
    public class Souvenir
    {
        public int ID { get; set; }

        public string Name { get; set; }


        public decimal Price { get; set; }
        public string Image { get; set; }
        public string Description { get; set; }
        public int CategoryID { get; set; }
        public int SupplierID { get; set; }

        public Category Category { get; set; }
        public Supplier Supplier { get; set; }

        public ICollection<OrderItem> OrderItems { get; set; }

    }
}

souvenirs/Controllers/ShoppingCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using souvenirs.Data;
using souvenirs.Models;
using Microsoft.AspNetCore.Authorization;

namespace souvenirs.Controllers
{
    [AllowAnonymous]
    [Authorize(Roles = "Member")]
    public class ShoppingCartController : Controller
    {
        ApplicationDbContext _context;

        public ShoppingCartController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);
            // Return the view
            return View(cart);
        }

        //
        // GET: /Store/AddToCart/5
        public ActionResult AddToCart(int id)
        {
            // Retrieve the album from the database
            var addedSouvenir = _context.Souvenirs
                .Single(tutorial => tutorial.ID == id);
            // Add it to the shopping cart
            var cart = ShoppingCart.GetCart(this.HttpContext);
            cart.AddToCart(addedSouvenir, _context);
            // Go back to the main store page for more shopping
            return RedirectToAction("Index", "MemberSouvenir");
        }

        public ActionResult RemoveFromCart(int id)
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);
            int itemCount = cart.RemoveFromCart(id, _context);
            return Redirect(Request.Headers["Referer"].ToString());
        }


        public ActionResult EmptyCart()
        {
            var cart = ShoppingCart.GetCart(this.HttpContext);
            cart.EmptyCart(_context);
            return Redirect(Request.Headers["Referer"].ToString());
        }
    }
}

souvenirs/Controllers/SouvenirsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using souvenirs.Data;
using souvenirs.Models;
using System.Net.Http.Headers;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using System.IO;
using Microsoft.AspNetCore.Authorization;

namespace souvenirs.Controllers
{
    [Authorize(Roles = "Admin")]
    public class SouvenirsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IHostingEnvironment _hostingEnv;

        public SouvenirsController(ApplicationDbContext context,IHostingEnvironment hEnv)
        {

            _context = context;
            _hostingEnv = hEnv;
        }

        // GET: Souvenirs
        public async Task<IActionResult> Index(
            string sortOrder,
            string currentFilter,
            string searchString,
            int? page)
        {
            ViewData["CurrentSort"] = sortOrder;
            ViewData["NameSortParm"] = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewData["PriceSortParm"] = sortOrder == "Price" ? "price_desc" : "Price";
            
            
            if(searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewData["CurrentFilter"] = searchString;

            var souvenirs = from s in _context.Souvenirs
                            select s;

            souvenirs = souvenirs.Include(s=>s.Category).Include(s=>s.Supplier);

            if (!String.IsNullOrEmpty(searchString))
            {
                souvenirs = souvenirs.Where(s => s.Name.Contains(searchString));
            }
            switch (sortOrder)
            {
                case "name_desc":
                    souvenirs = souvenirs.OrderByDescending(s => s.Name);
                    break;
                case "Price":
                    souvenirs = souvenirs.OrderBy(s => s.Price);
                    break;
                case "price_desc":
                    souvenirs = souvenirs.OrderByDescending(s => s.Price);
                    break;
                default:
                    souvenirs = souvenirs.OrderBy(s => s.Name);
                    break;
            }
            int pageSize = 3;
            return View(await PaginatedList<Souvenir>.CreateAsync(souvenirs.AsNoTracking(), page ?? 1, pageSize));
            //return View(await souvenirs.AsNoTracking().ToListAsync());
        }

        /*public async Task<IActionResult> CustomerIndex(int? categoryId, string currentFilter,string searchString,int? page,decimal? minPrice,decimal? maxPrice)
        {
            


            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewData["CurrentFilter"] = searchString;
            ViewData["CurrentCategory"] = categoryId;//put category id into current filter
            ViewData["minPrice"] = minPrice;
            ViewData["MaxPrice"] = maxPrice;

            var souvenirs = from s in _context.Souvenirs
                            select s;

            if (!String.IsNullOrEmpty(searchString))
            {
                souvenirs = souvenirs.Where(s => s.Name.Contains(searchString));
            }

            
            if(categoryId.HasValue)
            {
                souvenirs = souvenirs.Where(s => s.CategoryID == categoryId);
            }
            if (minPrice.HasValue)
            {
                souvenirs = souvenirs.Where(s => s.Price >= minPrice);
            }
            if (maxPrice.HasValue)
            {
                souvenirs = souvenirs.Where(s => s.Price <= maxPrice);
            }
            var categories = _context.Categories
                .AsNoTracking();

            ViewBag.Categories = categories;

            int pageSize = 3;
            return View(await PaginatedList<Souvenir>.CreateAsync(souvenirs.AsNoTracking(), page ?? 1, pageSize));
        }*/

        // GET: Souvenirs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var souvenir = await _context.Souvenirs
                .SingleOrDefaultAsync(m => m.ID == id);
            if (souvenir == null)
            {
                return NotFound();
            }

            return View(souvenir);
        }

        // GET: Souvenirs/Create
        public IActionResult Create()
        {
            PopulateCategoriesDropDownList();
            PopulateSuppliersDropDownList();
            return View();
        }

        // POST: Souvenirs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        /*public async Task<IActionResult> Create([Bind("ID,Name,Price,Image,Description,CategoryID,SupplierID")] Souvenir souvenir)
        {
            if (ModelState.IsValid)
            {
                _context.Add(souvenir);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(souvenir);
        }*/

        public async Task<IActionResult> Create([Bind("Name, Price, Description, CategoryID, SupplierID")] Souvenir souvenir,IList<IFormFile> _files)
        {
            var relativeName = "";
            var fileName = "";

            if(_files.Count < 1)
            {
                relativeName = "/Images/Souvenir/Default.jpg";
            }
            else
            {
                foreach (var file in _files)
                {
                    fileName = ContentDispositionHeaderValue
                                .Parse(file.ContentDisposition)
                                .FileName
                                .Trim('"');
                    relativeName = "/Images/Souvenir/" + DateTime.Now.ToString("ddMMyyyy-HHmmssffffff") + fileName;

                    using (FileStream fs =
                        System.IO.File.Create(_hostingEnv.WebRootPath + relativeName))
                    {
                        await file.CopyToAsync(fs);
                        fs.Flush();
                    }
                }
            }
            souvenir.Image = relativeName;
            try
            {
                if (ModelState.IsValid)
                {
                    _context.Add(souvenir);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
            }
            catch (DbUpdateException)
            {
                ModelState.AddModelError("","Unable to save changes." + "Try again and if the problem persists" + "see your system administrator.");
            }
            PopulateCategoriesDropDownList(souvenir.CategoryID);
            PopulateSuppliersDropDownList(souvenir.SupplierID);
            return View(souvenir);
        }

        // GET: Souvenirs/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            //var souvenir = await _context.Souvenirs.SingleOrDefaultAsync(m => m.ID == id);
            var souvenir = await _context.Souvenirs.AsNoTracking().SingleOrDefaultAsync(m => m.ID == id);

            if (souvenir == null)
            {
                return NotFound();
            }
            PopulateCategoriesDropDownList(souvenir.CategoryID);
            PopulateSuppliersDropDownList(souvenir.SupplierID);
            return View(souvenir);
        }

        // POST: Souvenirs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost,ActionName("Edit")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Name,Price,Description,CategoryID,SupplierID")] Souvenir souvenir, IList<IFormFile> _files)
        //public async Task<IActionResult> EditPost(int? id)
        {
            var relativeName = "";
            var fileName = "";
            if(id == null)
            {
                return NotFound();
            }
            var souvenirToUpdate = await _context.Souvenirs
                .SingleOrDefaultAsync(s => s.ID == id);
            if(await TryUpdateModelAsync<Souvenir>(souvenirToUpdate,"", s => s.CategoryID, s=>s.SupplierID, s=>s.Name, s=>s.Price,s=>s.Description))
            {
                try
                {
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateException)
                {
                    ModelState.AddModelError("", "Unable to save changes." + "Try again, and if the problem persists," + "see your system administrator.");
                }
                return RedirectToAction(nameof(Index));
     
            }
            if (id != souvenir.ID)
            {
                return NotFound();
            }
            if (_files.Count < 1)
            {
                relativeName = "/Images/Souvenir/Default.jpg";
            }
            else
            {
                foreach (var file in _files)
                {
                    fileName = ContentDispositionHeaderValue
                                .Parse(file.ContentDisposition)
                                .FileName
                                .Trim('"');

souvenirs/Views/Souvenirs/Create.cshtml
@model souvenirs.Models.Souvenir

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Souvenir</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Category" class="control-label"></label>
                    <select asp-for="CategoryID" class="form-control" asp-items="ViewBag.CategoryID">
                        
                    </select>
                <span asp-validation-for="CategoryID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Supplier" class="control-label"></label>
                <select asp-for="SupplierID" class="form-control" asp-items="ViewBag.SupplierID">
                    <option value="">--select Supplier--</option>
                </select>
                <span asp-validation-for="SupplierID" class="text-danger"></span>
            </div>
            <input type="file" name="_files" id="_files" />
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

souvenirs/Views/Souvenirs/CustomerIndex.cshtml
@model PaginatedList<souvenirs.Models.Souvenir>

@{
    ViewData["Title"] = "Index";
}

<section class="row">
    <div class="col-lg-2">
        <span>Category List</span>
        <table class="table">
            <thead>
                <tr>
                    <th>
                        category name
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>

                <tr>
                    <td>
                        <a asp-area="" asp-controller="Souvenirs" asp-action="CustomerIndex">All Category</a>

                    </td>

                </tr>
                @{var categories = ViewBag.Categories as IEnumerable<souvenirs.Models.Category>;}
                @foreach (var item in categories)
                {

                    <tr>
                        <td>
                            <a asp-area="" asp-controller="Souvenirs" asp-action="CustomerIndex" asp-route-categoryId="@item.ID">@Html.DisplayFor(modelItem => item.CategoryName)</a>

                        </td>

                    </tr>
                }
            </tbody>
        </table>
    </div>
    <div class="col-lg-10">
        <form asp-action="CustomerIndex" method="get">
            <div class="form-actions no-color">
                <p>
                    Find by name: <input type="text" name="SearchString" value="@ViewData["currentfilter"]" />
                    find by price: <input type="number" name="minPrice" value="@ViewData["minPrice"]" />~<input type="number" name="maxPrice" value="@ViewData["maxPrice"]" />
                    <input type="hidden" value="@ViewData["CurrentCategory"]" name="categoryId" />
                    <input type="submit" value="Search" class="btn btn-default" />
                    <a asp-action="Index">Back to Full List</a>
                </p>
            </div>
        </form>

        <table class="table">
            <thead>
                <tr>
                    <th>image</th>
                    <th>price</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    var imgUrl = Href("~" + item.Image);
                    var errImg = Href("~/images/Souvenir/Unitec.jpg");
                <tr>
                    <td>
                        <img style="width:250px;height:auto;" src="@imgUrl" alt="SouvenirImage"
                             onerror="this.onerror = null;this.src='@errImg'" />
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Price)
                    </td>
                    <td>
                        <a asp-action="Details" asp-route-id="@item.ID">Details</a>
                    </td>
                    <td>
                        <a asp-action="AddToCart" asp-controller="ShoppingCart" asp-route-id="@item.ID">
                            <span class="glyphicon glyphicon-shopping-cart"></span>
                            Add To Cart
                        </a>
                    </td>

                </tr>
                }
            </tbody>
        </table>

        @{
            var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
            var nextDisabled = !Model.HasNextPage ? "disabled" : "";
        }
        <a asp-action="CustomerIndex"
           asp-route-page="@(Model.PageIndex - 1)"
           asp-route-currentFilter="@ViewData["CurrentFilter"]"
           asp-route-categoryId="@ViewData["CurrentCategory"]"
           asp-route-minPrice="@ViewData["minPrice"]"
           asp-route-maxPrice="@ViewData["maxPrice"]"
           class="btn btn-default @prevDisabled">
            Previous
        </a>
        <a asp-action="CustomerIndex"
           asp-route-page="@(Model.PageIndex + 1)"
           asp-route-currentFilter="@ViewData["CurrentFilter"]"
           asp-route-categoryId="@ViewData["CurrentCategory"]"
           asp-route-minPrice="@ViewData["minPrice"]"
           asp-route-maxPrice="@ViewData["maxPrice"]"
           class="btn btn-default @nextDisabled">
            Next
        </a>

    </div>
</section>

souvenirs/Views/Souvenirs/Delete.cshtml
@model souvenirs.Models.Souvenir

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h3>@TempData["OrderUsed"]</h3>
    <h4>Souvenir</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ID)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ID)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Image)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Image)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Category)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Category.CategoryName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Supplier)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Supplier.SupplierName)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

souvenirs/Views/Souvenirs/Details.cshtml
@model souvenirs.Models.Souvenir

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Souvenir</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ID)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ID)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Image)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Image)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Category)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Category.CategoryName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Supplier)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Supplier.SupplierName)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

souvenirs/Views/Souvenirs/Edit.cshtml
@model souvenirs.Models.Souvenir

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Souvenir</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group invisible">
                <label asp-for="ID" class="control-label"></label>
                <div>@Html.DisplayFor(model => model.ID)</div>
                
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CategoryID" class="control-label"></label>
                <select asp-for="CategoryID" class="form-control" asp-items="ViewBag.CategoryID"></select>
            </div>
            <div class="form-group">
                <label asp-for="SupplierID" class="control-label"></label>
                <select asp-for="SupplierID" class="form-control" asp-items="ViewBag.SupplierID">
                    <option value="">--select Supplier--</option>
                </select>
                <span asp-validation-for="SupplierID" class="text-danger"></span>
            </div>
            <input type="file" name="_files" id="_files" />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

souvenirs/Views/Souvenirs/Index.cshtml
@model PaginatedList<souvenirs.Models.Souvenir>

@{
    ViewData["Title"] = "Index";
}

<h2>Souvenir</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>

<form asp-action="Index" method="get">
    <div class="form-actions no-color">
        <p>
            Find by name: <input type="text" name="SearchString" value="@ViewData["currentfilter"]" />
            <input type="submit" value="Search" class="btn btn-default" />
            <a asp-action="Index">Back to Full List</a>
        </p>
    </div>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                Image
            </th>
            <th>
                <a asp-action="Index" asp-route-sortOrder="@ViewData["NameSortParm"]">Name</a>
            </th>
            <th>
                <a asp-action="Index" asp-route-sortOrder="@ViewData["PriceSortParm"]">Price</a>
            </th>
            <th>
                Description
            </th>
            <th>
                Category
            </th>
            <th>
                Supplier
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            var imgUrl = Href("~" + item.Image);
            var errImg = Href("~/images/Souvenir/Unitec.jpg");
        <tr>
            <td>
                <img style="width:250px;height:auto;" src="@imgUrl" alt="SouvenirImage"
                     onerror="this.onerror = null;this.src='@errImg'" />
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Category.CategoryName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Supplier.SupplierName)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
            </td>


        </tr>
        }
    </tbody>
</table>
@{ 
    var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !Model.HasNextPage ? "disabled" : "";
}
<a asp-action="Index"
   asp-route-sortOrder ="@ViewData["CurrentSort"]"
   asp-route-page ="@(Model.PageIndex - 1)"
   asp-route-currentFilter ="@ViewData["CurrentFilter"]"
   class="btn btn-default @prevDisabled">
    Previous
</a>
<a asp-action="Index"
   asp-route-sortOrder="@ViewData["CurrentSort"]"
   asp-route-page="@(Model.PageIndex + 1)"
   asp-route-currentFilter="@ViewData["CurrentFilter"]"
   class="btn btn-default @nextDisabled">
    Next
</a>